baseurl = "http://docs.scoutred.com/"
languageCode = "en-us"
title = "Scoutred API"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-51537973-4"
publishDir = "docs"

[params]
	# General information
	author = "Scoutred"
	description = "Scoutred API developer documentation"
	copyright = ""

	# Repository
	provider = ""
	repo_url = "https://github.com/scoutred/docs"

	version = "v1"
	logo = "images/scoutred-icon.svg"
	favicon = "https://scoutred.com/static/shortcut-icons/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
	primary = "blue-grey"
	accent  = "teal"

    [params.font]
	text = "Ubuntu"
	code = "Ubuntu Mono"

[social]
twitter = "scoutred_"
github  = "scoutred"
email   = "hello@scoutred.com"


[[menu.main]]
name   = "Introduction"
url    = "/"
weight = 1

[[menu.main]]
name   = "Authentication"
url    = "authentication/"
weight = 10

[[menu.main]]
name   = "Addresses"
url    = "addresses/"
weight = 20

[[menu.main]]
name   = "Community Plans"
url    = "community_plans/"
weight = 30

[[menu.main]]
name   = "Overlays"
url    = "overlays/"
weight = 40

[[menu.main]]
name   = "Parcels"
url    = "parcels/"
weight = 50

[[menu.main]]
name   = "Zoning"
url    = "zoning/"
weight = 60

[blackfriday]
smartypants	= true
fractions = true
smartDashes = true
plainIDAnchors = true
